import pandas as pd

df = pd.read_csv("property_100.csv", sep=";")

# delete unwanted column in the dtat
df = df.drop(
    [
        "Available as of",
        "Available date",
        "Number of floors",
        "Construction year",
        "Floor",
        "Number of floors",
        "Building condition",
        "Number of frontages",
        "Surroundings type",
        "Living room surface",
        "Kitchen surface",
        "Bedroom 1 surface",
        "Bathrooms",
        "Accessible for disabled people",
        "Visio phone",
        "Primary energy consumption",
        "Reference number of the EPC report",
        "CO₂ emission",
        "Yearly theoretical total energy consumption",
        "As built plan",
        "Heating type",
        "Thermic solar panels",
        "Double glazing",
        "Planning permission obtained",
        "Subdivision permit",
        "Possible priority purchase right",
        "Flood zone type",
        "Latest land use designation",
        "Cadastral income",
        "Tenement building",
        "Address",
        "Website",
        "External reference",
        "Covered parking spaces",
        "Outdoor parking spaces",
        "Bedroom 2 surface",
        "Bedroom 3 surface",
        "Office surface",
        "Office",
        "Dining room",
        "Basement",
        "Armored door",
        "Caretaker",
        "Monthly charges",
        "Street frontage width",
        "Shower rooms",
        "Intercom",
        "Total ground floor buildable",
        "Extra information",
        "Agent's name",
        "Living room",
        "Dressing room",
        "Laundry room",
        "Professional space",
        "Gas, water & electricity",
        "Secure access / alarm",
        "Photovoltaic solar panels",
        "Property name",
        "Terrace orientation",
        "Air conditioning",
        "Common water heater",
        "TV cable",
        "Connection to sewer network",
        "Jacuzzi",
        "Sauna",
        "E-level (overall energy performance)",
        "Heat pump",
        "Proceedings for breach of planning regulations",
        "Garden orientation",
        "Width of the lot on the street",
        "Virtual visit",
        "Bedroom 4 surface",
        "Attic",
        "How many fireplaces?",
        "Professional space surface",
        "Basement surface",
        "Attic surface",
        "Obligation to build",
        "Bedroom 5 surface",
        "Land is facing street",
        "Wooded land",
        "Plot at rear",
        "Flat land",
        "Internet",
        "Conformity certification for fuel tanks",
        "Type of building",
        "Lump sum",
        "Monthly annuity",
        "Indexed annuity",
        "Reversionary annuity",
        "Bare ownership sale",
        "Number of annuitants",
        "Age of annuitant",
        "Maximum duration of annuity",
    ],
    axis=1,
    inplace=True,
)

df.to_csv("cleaned_data100.csv", index=False, sep=";")

